// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6KhR0Io0ADIXceYWL-UgeOxAcq6nawVQ',
    appId: '1:1062805989888:web:36ebdd23913cf2787886e5',
    messagingSenderId: '1062805989888',
    projectId: 'mini-ecommerce-29b6d',
    authDomain: 'mini-ecommerce-29b6d.firebaseapp.com',
    storageBucket: 'mini-ecommerce-29b6d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ_rsYZdnGufvOHmmpvxlfuP7ccZyUfKM',
    appId: '1:1062805989888:android:fc5850fd95648e437886e5',
    messagingSenderId: '1062805989888',
    projectId: 'mini-ecommerce-29b6d',
    storageBucket: 'mini-ecommerce-29b6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzuUgzMvjaO7LJBomp4DqsBwg2Jo_Vz8Y',
    appId: '1:1062805989888:ios:019feeda7aafb50a7886e5',
    messagingSenderId: '1062805989888',
    projectId: 'mini-ecommerce-29b6d',
    storageBucket: 'mini-ecommerce-29b6d.appspot.com',
    iosBundleId: 'com.example.miniEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzuUgzMvjaO7LJBomp4DqsBwg2Jo_Vz8Y',
    appId: '1:1062805989888:ios:18c7ddcaf0d293177886e5',
    messagingSenderId: '1062805989888',
    projectId: 'mini-ecommerce-29b6d',
    storageBucket: 'mini-ecommerce-29b6d.appspot.com',
    iosBundleId: 'com.example.miniEcommerce.RunnerTests',
  );
}
